stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - apt update
    - apt install -y libclang-dev clang build-essential:native lsb-release omniidl snacc
      # Debian still does not have wireshark-3.0, build it
    - curl -s https://www.wireshark.org/download/src/wireshark-3.0.9.tar.xz -o wireshark.tar.xz
    - tar -xf wireshark.tar.xz
    - cd wireshark-3.0.9 &&
        tools/debian-setup.sh --install-optional --install-deb-deps --install-test-deps -y &&
        dpkg-buildpackage -b -uc -us -jauto 
    - dpkg -i *.deb
      # build wireshark plugin
    - (cd wireshark-kafka && cargo build --verbose --release)
